### PR TITLE
Update mk_series.R

### PR DESCRIPTION
**Pull request by sguidi11**
I guess the double column in row 33 isn't needed anymore

### CODE REVIEW

**Comment by sguidi11** [comment]
I just discovered your package and i am learning how to collaborate using git.
Great thanksl

**Comment by krose** [comment]
Hi @sguidi11 .. You might wan't to look at the latest version. I had a few fixes and additions on my laptop that wasn't on github.

**Comment by krose** [comment]
Also.. I changed the name of the package and a few of the functions. Let me know if you run into any issues.

**Comment by sguidi11** [comment]
HI Kenneth,
I am first of all trying to understand how to use github.
Is it correct to:

1)    Branch your project

2)    Modify (ev.improve) suggest,….changes

3)    Pull request

4)    You authorize / not authorize changes

Makes sense ?

**Comment by krose** [comment]
That's pretty accurate, but google branch vs. fork.

You fork a project -> you create a new branch -> modify/add code -> create a pull request -> I merge your pull request (or make suggestions to improve your pull request).

**Comment by sguidi11** [comment]
No need for me to fork the project! Credit on you work!
I meant “branch”.

Cool! Thanks.

Another comment. What about making the user_agent a bit more generic?
By setting a simple filter rule, “wattsight” could block us easily.

**Comment by krose** [comment]
No problem.. I hope you will get some value out of it.

About the user_agent. I spoke to wattsight when I made it so the developer
know that it exists, though I don't think he has tried it. Let's keep it
that way until it's a problem and then we can speak to Wattsight if it
becomes an issue.

**Comment by sguidi11** [comment]
Good like this then. It is easily modifiable eventually.

I am right now writing a function to listen to the API events.

**Comment by krose** [comment]
Cool.. sounds great.

**Pull request closed without merging**
